analytics

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,14 +1,14 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+# #!/usr/bin/env sh
+# . "$(dirname -- "$0")/_/husky.sh"
 
-echo "Running pre-commit hook...🍺"
+# echo "Running pre-commit hook...🍺"
 
-npx lint-staged
-echo "ESLint & Prettier check completed successfully. ✅ "
+# npx lint-staged
+# echo "ESLint & Prettier check completed successfully. ✅ "
 
-git add -A .
-pnpm build || (
-  echo "Build failed. ❌ "
-  exit 1
-)
-echo "Build completed successfully. ✅ "
+# git add -A .
+# pnpm build || (
+#   echo "Build failed. ❌ "
+#   exit 1
+# )
+# echo "Build completed successfully. ✅ "
